name: Create and publish Docker images (Staging)

on:
  workflow_dispatch:
  push:
    branches:
      - staging

env:
  GITHUB_SHA: ${{ github.sha }}
  AWS_REGION: ca-central-1
  GHCR_REPO: ghcr.io/${{ github.repository }}
  WEB_TAGS: >-
    ${{
      github.repository == 'cds-snc/cra-arc-upd-tbpc' && (
        '211125499457.dkr.ecr.ca-central-1.amazonaws.com/cra-upd-dashboard-staging:latest'
      ) || format(
        'ghcr.io/{0}/web:latest', github.repository
      )
    }}
  DATA_IMPORT_TAGS: '211125499457.dkr.ecr.ca-central-1.amazonaws.com/cra-upd-dashboard-staging-data-import:latest'
  UPDATE_DB_TAGS: '211125499457.dkr.ecr.ca-central-1.amazonaws.com/cra-upd-dashboard-staging-update-db:latest'

jobs:
  cache-deps:
    name: Validate npm cache for staging branch and get affected apps
    runs-on: ubuntu-latest
    outputs:
      affected_apps: ${{ steps.affected-apps.outputs.affected_apps }}
    steps:
      - name: Checkout [staging branch]
        uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          filter: tree:0
          ref: ${{ github.repository == 'cds-snc/cra-arc-upd-tbpc' && 'staging' || 'main' }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24.11.0

      - name: Use the node_modules cache if available [npm]
        id: use-npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-24.11.0-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.use-npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Find affected SHAs
        id: affected-shas
        uses: nrwl/nx-set-shas@v4 # Sets the NX_BASE and NX_HEAD env variables
        with:
          main-branch-name: staging # The branch used to find the base SHA

      - name: Check if Python projects are affected
        id: check-python
        # Manually check if files under the python directory have changed with git using the SHAs set in the previous step
        run: |
          AFFECTED_PYTHON_FILES=$(git diff --name-only ${{ env.NX_BASE }} ${{ env.NX_HEAD }} | grep "^python/" || true)
          if [ -z "$AFFECTED_PYTHON_FILES" ]; then
            echo "No Python files affected."
            echo "python_affected=false" >> $GITHUB_OUTPUT
          else
            echo "Python files affected: $AFFECTED_PYTHON_FILES"
            echo "python_affected=true" >> $GITHUB_OUTPUT
          fi

      - name: Determine affected apps
        id: affected-apps
        run: |
          AFFECTED_APPS=$(npx nx show projects --affected --with-target build --type app --json --base ${{ env.NX_BASE }} --head ${{ env.NX_HEAD }})

          if [ "${{ steps.check-python.outputs.python_affected }}" == "true" ]; then
            if [ -z "$AFFECTED_APPS" ]; then
              AFFECTED_APPS="[\"python\"]"
            else
              AFFECTED_APPS=$(echo $AFFECTED_APPS | jq '. + ["python"]')
            fi
          fi

          echo "Affected apps: $AFFECTED_APPS"
          echo "affected_apps=$AFFECTED_APPS" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: cache-deps
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Audit DNS requests
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
        uses: cds-snc/dns-proxy-action@main
        env:
          DNS_PROXY_FORWARDTOSENTINEL: 'true'
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.repository == 'cds-snc/cra-arc-upd-tbpc' && 'staging' || 'main' }}

      - name: Configure aws credentials using OIDC
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::211125499457:role/cra-arc-upd-tbpc-apply
          role-session-name: ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Log in to the Container registry
        if: github.repository != 'cds-snc/cra-arc-upd-tbpc'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (web)
        if: contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/performance_base/Dockerfile
          target: web
          push: true
          tags: ${{ env.WEB_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (nginx)
        if: github.repository != 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'upd')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/performance_base/Dockerfile
          target: nginx
          push: true
          tags: ${{ env.GHCR_REPO }}/nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (db-updater)
        if: github.repository != 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'db-updater')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/performance_base/Dockerfile
          target: db-updater
          push: true
          tags: ${{ env.GHCR_REPO }}/db-updater:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (data-import)
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'python')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ecs-tasks/data-import/Dockerfile
          push: true
          tags: ${{ env.DATA_IMPORT_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image (update-db)
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && (contains(fromJson(needs.cache-deps.outputs.affected_apps), 'update-db-task') || contains(fromJson(needs.cache-deps.outputs.affected_apps), 'python'))
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ecs-tasks/update-db/Dockerfile
          push: true
          tags: ${{ env.UPDATE_DB_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Restart ECS
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
        run: |
          aws ecs update-service --cluster cra-upd-dashboard-cluster --service cra-upd-dashboard-app-service --force-new-deployment > /dev/null 2>&1

      # Allow this step to fail so we can handle success/failure and report it to slack. By default it waits for 10 minutes
      - name: Wait for ECS Stability
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
        id: ecs_wait
        continue-on-error: true
        run: |
          echo "Wait for 15 minutes for ECS to stabilize.."
          sleep 300 # Sleep for 5 minutes. The ecs wait command waits for an additional 10 minutes
          aws ecs wait services-stable \
            --cluster cra-upd-dashboard-cluster \
            --services cra-upd-dashboard-app-service

      # todo: add this back in once we have a stable deployment
      # # Slack notification on failed ECS wait
      # - name: Slack Notify Failure
      #   if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api') && steps.ecs_wait.outcome == 'failure'
      #   run: |
      #     curl -X POST -H 'Content-type: application/json' \
      #     --data '{"text": "‚ùå ECS deployment for cra-upd-dashboard (staging) failed to stabilize."}' \
      #     ${{ secrets.SLACK_NOTIFY_WEBHOOK }}

      - name: Report deployment to Sentinel
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api') && steps.ecs_wait.outcome == 'success'
        uses: cds-snc/sentinel-forward-data-action@main
        with:
          input_data: '{"product": "cra-upd-dashboard", "version": "${{ github.sha }}", "repository": "${{ github.repository }}", "environment": "staging"}'
          log_type: CDS_Product_Deployment_Data
          log_analytics_workspace_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          log_analytics_workspace_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: Docker generate SBOM
        if: github.repository == 'cds-snc/cra-arc-upd-tbpc' && contains(fromJson(needs.cache-deps.outputs.affected_apps), 'api')
        uses: cds-snc/security-tools/.github/actions/generate-sbom@34794baf2af592913bb5b51d8df4f8d0acc49b6f # v3.2.0
        env:
          TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
        with:
          docker_image: ${{ env.WEB_TAGS }}
          dockerfile_path: './Dockerfile'
          sbom_name: 'cra-upd-dashboard'
          token: '${{ secrets.GITHUB_TOKEN }}'
